export const FETCH_STORES = 'FETCH_STORES';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_ERROR = 'FETCH_STORES_ERROR';
export const UPDATE_PRODUCT_DATA = 'UPDATE_PRODUCT_DATA';
export const ADD_PRODUCT = 'ADD_PRODUCT';