export const FETCH_STORES = 'FETCH_STORES';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_ERROR = 'FETCH_STORES_ERROR';
export const UPDATE_PRODUCT_DATA = 'UPDATE_PRODUCT_DATA';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';